version: '3'
services:
  web:
    build: ./
    environment:
      - PYTHONBUFFERED=1

    env_file:
      - app.env
      # #FOR POSTGRES
      # - POSTGRES_USER=hello_flask
      # - POSTGRES_PASSWORD=hello_flask
      # - POSTGRES_DB=hello_flask_dev
      # - POSTGRES_HOST=db
      # - POSTGRES_PORT=5432
      # #FOR REDIS
      # - REDIS_HOST=redis
      # - REDIS_PORT=6379
    ports:
      # - "80:80"
      - ${APP_PORT}:${APP_PORT}
    links:
      - redis
      - db
  redis:
    image: redis:6.0.8
    ports:
      # - "6379:6379"
      - ${REDISH_PORT}:${REDISH_PORT}
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # environment:
    #   - POSTGRES_USER=hello_flask
    #   - POSTGRES_PASSWORD=hello_flask
    #   - POSTGRES_DB=hello_flask_dev
    env_file:
      - db.env

    ports:
      # - "5432:5432"
      - ${DB_PORT}:${DB_PORT}
    
volumes:
  postgres_data:

